export const SET_PROVINCEDATA = 'SET_PROVINCEDATA';
export const SET_WORLDDATA = 'SET_WORLDDATA';
export const SET_WORLDDATALIST = 'SET_WORLDDATALIST';
export const SET_GLOBALTOTAL = 'SET_GLOBALTOTAL';

export default {};
